import ScanStep from '@/types/scan-step';

export const scanSteps: ScanStep[] = [
  {
    target: 'Local email accounts',
    action: 'Collecting stored email identifiers',
    result: 'No exposed email addresses',
    severity: 'safe',
    duration: 600,
  },
  {
    target: 'Keychain storage',
    action: 'Reading encrypted credential entries',
    result: 'No direct leaks found',
    severity: 'safe',
    duration: 900,
  },
  {
    target: 'Keychain storage',
    action: 'Analyzing password strength',
    result: 'Weak passwords detected',
    severity: 'warning',
    duration: 750,
  },
  {
    target: 'Browser autofill data',
    action: 'Scanning saved login forms',
    result: 'Reused credentials identified',
    severity: 'warning',
    duration: 1000,
  },
  {
    target: 'Browser autofill data',
    action: 'Checking form submission history',
    result: 'No external exposure detected',
    severity: 'safe',
    duration: 450,
  },
  {
    target: 'Installed applications',
    action: 'Reviewing app-level credential storage',
    result: 'Potential exposure detected',
    severity: 'leaked',
    duration: 1100,
  },
  {
    target: 'Installed applications',
    action: 'Analyzing authentication persistence',
    result: 'Risky session retention found',
    severity: 'warning',
    duration: 650,
  },
  {
    target: 'Clipboard history',
    action: 'Inspecting recent clipboard content',
    result: 'Sensitive data fragments found',
    severity: 'leaked',
    duration: 550,
  },
  {
    target: 'Clipboard history',
    action: 'Verifying clipboard cleanup status',
    result: 'No active threats',
    severity: 'safe',
    duration: 400,
  },
  {
    target: 'Local cache files',
    action: 'Scanning cached authentication tokens',
    result: 'No valid tokens exposed',
    severity: 'safe',
    duration: 850,
  },
  {
    target: 'Local cache files',
    action: 'Reviewing temporary session data',
    result: 'Expired credentials detected',
    severity: 'warning',
    duration: 700,
  },
  {
    target: 'System permissions',
    action: 'Analyzing permission configuration',
    result: 'Overprivileged access detected',
    severity: 'warning',
    duration: 800,
  },
  {
    target: 'System permissions',
    action: 'Verifying permission usage patterns',
    result: 'No abnormal activity',
    severity: 'safe',
    duration: 500,
  },
  {
    target: 'Device memory',
    action: 'Scanning volatile memory regions',
    result: 'No plaintext credentials found',
    severity: 'safe',
    duration: 1150,
  },
  {
    target: 'Device memory',
    action: 'Inspecting memory retention behavior',
    result: 'Potential data residue detected',
    severity: 'warning',
    duration: 750,
  },
  {
    target: 'Background processes',
    action: 'Monitoring credential-related activity',
    result: 'Suspicious behavior detected',
    severity: 'warning',
    duration: 950,
  },
  {
    target: 'Background processes',
    action: 'Validating process integrity',
    result: 'No confirmed threats',
    severity: 'safe',
    duration: 600,
  },
  {
    target: 'Local security index',
    action: 'Aggregating scan results',
    result: 'Multiple risk factors identified',
    severity: 'leaked',
    duration: 1050,
  },
  {
    target: 'Local security index',
    action: 'Calculating credential exposure score',
    result: 'Elevated exposure risk',
    severity: 'leaked',
    duration: 850,
  },
  {
    target: 'Final assessment',
    action: 'Finalizing device credential scan',
    result: 'Scan completed with detected risks',
    severity: 'leaked',
    duration: 800,
  },
];
