const fakeDescriptions = [
  'In October 2013, software giant Adobe suffered a massive data breach that impacted at least 153 million user accounts. The compromised data included internal ID numbers, usernames, emails, and encrypted passwords, alongside plain text password hints. The breach also exposed customer names and payment card numbers for a smaller subset of users. Comprehensive analysis of the cryptography involved is available in the blog post regarding the Adobe data breach.',
  'In late 2016, a massive collection of credential stuffing lists known as "Exploit.in" appeared on underground hacking forums. This aggregation compiled data from various smaller breaches into a single searchable list. The dump included 593 million unique email addresses and corresponding passwords, posing a severe risk for users who reuse credentials across services. Further analysis of this incident is available in the article regarding the Exploit.in Combo List.',
  'In May 2019, the graphic design tool Canva suffered a data breach impacting approximately 137 million subscribers. The exposed data included email addresses, names, cities, and bcrypt-hashed passwords. The incident was attributed to a hacker known as GnosticPlayers, who claimed responsibility for the attack and contacted media outlets to publicize the theft. Full details on the scope of the exposure are outlined in the security notice regarding the Canva breach.',
  'In February 2019, security researchers discovered an unprotected MongoDB instance belonging to email validation service Verifications.io. The database contained approximately 763 million unique email addresses, many comprising names, phone numbers, and other personal data. While passwords were not included, the sheer scale of personal information exposed resulted in a significant privacy impact. Additional insights can be found in the report titled The 800 Million Record Verifications.io Data Breach.',
  'In May 2016, a dataset containing email addresses and password hashes for 164 million LinkedIn accounts was put up for sale on a dark web marketplace. The data originally stemmed from a breach in 2012, but the full extent was not revealed until years later. This exposure forced a global password reset for millions of users. A complete breakdown of the timeline and impact is provided in the update on the 2016 LinkedIn Data Breach.',
  'In September 2019, game developer Zynga announced a breach affecting players of "Words with Friends" and "Draw Something." The incident exposed over 173 million unique email addresses, along with usernames and salted SHA-1 password hashes. The breach was part of a larger campaign targeting mobile gaming platforms by a known threat actor. More information on the compromised data is available in the report on the Zynga poker and game data breach.',
  'In December 2016, a large credential database dubbed the "Anti Public Combo List" was circulated within the hacker community. Distinct from other collections, this list aggregated 458 million unique email addresses and plain text passwords aimed at facilitating account takeovers. The breach highlights the dangers of password reuse, and more specifics are detailed in the post regarding the Anti Public data dump.',
  'In June 2020, a database containing more than 270 million records from the user-generated story platform Wattpad was sold on a hacking forum. The exposed information included names, email addresses, and bcrypt-hashed passwords. While financial information was not compromised, the breach significantly impacted user privacy across the globe. Further details are documented in the investigation of the Wattpad data breach.',
  'In 2016, a repository of data containing 360 million MySpace accounts appeared on the "Real Deal" dark web market. The breach, which actually occurred years prior, included email addresses, usernames, and weak SHA-1 password hashes for accounts created prior to June 11, 2013. The scale of the leak makes it one of the most significant historical breaches. Full context is provided in the detailed write-up of the MySpace data sale.',
  'In January 2017, a misconfigured backup by spam operator River City Media exposed a massive database of 1.37 billion email records. The leak included real names, IP addresses, and physical addresses, providing a rare look into the operations of a large-scale spam network. The discovery was made by security researcher Chris Vickery. A full explanation of the findings is available in the article titled Inside the River City Media Spam Machine.',
];

export default function getFakeDescription() {
  const num = Math.floor(Math.random() * 10);
  return fakeDescriptions[num];
}
